- name: LBaaS projects install
  hosts: localhost
  connection: local
  tasks:
    - name: create Projects directory
      ansible.builtin.file:
        path: ~/Projects
        state: directory
        mode: '0755'
    - name: create iac-lbaas directory
      ansible.builtin.file:
        path: ~/Projects/iac-lbaas
        state: directory
        mode: '0755'
    - name: clone ctrl-gru project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/ctrl-gru.git
        # if i dont set all the path it will clone the content of project in iac-lbaas/ dir
        dest: ~/Projects/iac-lbaas/ctrl-gru         
        single_branch: yes
        version: main
    - name: clone cli project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/cli.git
        dest: ~/Projects/iac-lbaas/cli
        single_branch: yes
        version: main
    - name: clone api project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/api.git
        dest: ~/Projects/iac-lbaas/api
        single_branch: yes
        version: main
    - name: clone go-sdk project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/go-sdk.git
        dest: ~/Projects/iac-lbaas/go-sdk
        single_branch: yes
        version: main
    - name: clone minion project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/agents/minion.git        
        dest: ~/Projects/iac-lbaas/agents/minion/
        single_branch: yes
        version: main
    - name: clone rialto-alteon project
      ansible.builtin.git:
        repo: git@gitlab.tech.orange:iac-lbaas/agents/rialto-alteon.git        
        dest: ~/Projects/iac-lbaas/agents/rialto-alteon/
        single_branch: yes
        version: main
